spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost/viewpoint?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    check-template: true
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
server:
  port: 8080
ftp:
  port: 21
  hostname: 192.168.1.145
  userName: ftp_test
  password: 123456
  basePath: /home/ftp_test
  fileUploadPath: http://192.168.1.145
imooc:
  security:
    browser:
      loginType:  REDIRECT
